const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: '1234',
      role: "Admin",
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: '5678',
      role: "User",
    }
  ],
  products: [
    {
      // _id: '1',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/products/belt-1.png',
      price: 120,
      countInStock : 5,
      brand: 'Nike',
      rating: 1,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '2',
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: '/images/products/belt-2.png',
      price: 100,
      countInStock :10,
      brand: 'Adidas',
      rating: 1.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '3',
      name: 'Lacoste Free Shirt',
      category: 'Shirts',
      image: '/images/products/belt-3.png',
      price: 220,
      countInStock :12,
      brand: 'Lacoste',
      rating: 2.0,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      // _id: '4',
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: '/images/products/pant-1.png',
      price: 78,
      countInStock :5,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      // _id: '5',
      name: 'Puma Slim Pant',
      category: 'Pants',
      image: '/images/products/shirt-1.png',
      price: 65,
      countInStock :9,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '6',
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: '/images/products/pant-2.png',
      price: 139,
      countInStock :22,
      brand: 'Adidas',
      rating: 5.0,
      numReviews: 15,
      description: 'high quality product',
    },
  ], 
};

module.exports =  data;